name: Spellcheck

on:
  pull_request:
    branches: [ "**" ]

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CSpell
        run: npm install -g cspell

      - name: Run Spell Check
        run: cspell "**/*.md"